name: ZAP
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run my app
        run: |
          npm install
          nohup npm run start &

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          target: http://localhost:4200
